import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "About DevDrews | Ethical Hacker & Software Engineer",
  description:
    "Learn about Andrews, an experienced software engineer and ethical hacking enthusiast from Ghana. Discover his journey, skills, and passion for cybersecurity across Kumasi, Accra, and Konongo.",
  keywords: [
    "Andrews",
    "DevDrews Blog",
    "Andrews Osei",
    "Andrews Osei-Agyemang",
    "Andrews Osei Agyemang",
    "hacker",
    "hacker in ghana",
    "hacker in kumasi",
    "hacker in accra",
    "hacker in konongo",
    "ethical hacker",
    "ethical hacker in ghana",
    "ethical hacker in kumasi",
    "ethical hacker in accra",
    "ethical hacker in konongo",
    "software engineer",
    "software engineer in ghana",
    "software engineer in kumasi",
    "software engineer in accra",
    "software engineer in konongo",
    "cybersecurity",
    "cybersecurity in ghana",
    "cybersecurity in kumasi",
    "cybersecurity in accra",
    "cybersecurity in konongo",
    "web development",
    "web development in ghana",
    "web development in kumasi",
    "web development in accra",
    "web development in konongo",
    "penetration testing",
    "penetration testing in ghana",
    "penetration testing in accra",
    "penetration testing in kumasi",
    "penetration testing in konongo",
    "IT security",
    "IT security in ghana",
    "IT security in accra",
    "IT security in kumasi",
    "IT security in konongo",
    "coding",
    "coding in ghana",
    "coding in kumasi",
    "coding in accra",
    "coding in konongo",
    "tech skills",
    "tech skills in ghana",
    "tech skills in kumasi",
    "tech skills in accra",
    "tech skills in konongo",
    "professional profile",
    "professional profile in ghana",
    "professional profile in accra",
    "professional profile in kumasi",
    "professional profile in konongo",
  ],
  openGraph: {
    title: "About DevDrews | Ethical Hacker & Software Engineer in Ghana",
    description:
      "Learn about Andrews, an experienced software engineer and ethical hacking enthusiast from Ghana. Discover his journey, skills, and passion for cybersecurity across Kumasi, Accra, and Konongo.",
    type: "website",
    locale: "en_US",
    siteName: "DevDrews Blog",
  },
  twitter: {
    card: "summary_large_image",
    site: "@devdrews1",
    creator: "@devdrews1",
    title: "About DevDrews | Ethical Hacker & Software Engineer in Ghana",
    description:
      "Learn about Andrews, an experienced software engineer and ethical hacking enthusiast from Ghana. Discover his journey, skills, and passion for cybersecurity across Kumasi, Accra, and Konongo.",
  },
  robots: {
    index: true,
    follow: true,
    googleBot: {
      index: true,
      follow: true,
      "max-video-preview": -1,
      "max-image-preview": "large",
      "max-snippet": -1,
    },
  },
  alternates: {
    canonical: "https://www.devdrews.com/about",
  },
  authors: [{ name: "Andrews Osei-Agyemang" }],
  verification: {
    google: "f_j4kSgrnYfVxaesQbBa5bTT5RNy_KDuR90YafK0Rqw",
  },
  other: {
    "google-site-verification": "f_j4kSgrnYfVxaesQbBa5bTT5RNy_KDuR90YafK0Rqw",
  },
};

const structuredData = {
  "@context": "https://schema.org",
  "@type": "Person",
  name: "Andrews Osei-Agyemang",
  alternateName: "DevDrews",
  description:
    "Experienced software engineer and ethical hacking enthusiast from Ghana",
  jobTitle: "Software Engineer & Ethical Hacker",
  url: "https://www.devdrews.com",
  sameAs: ["https://twitter.com/devdrews1"],
  knowsAbout: [
    "Ethical Hacking",
    "Software Engineering",
    "Cybersecurity",
    "Web Development",
    "Penetration Testing",
    "IT Security",
  ],
  workLocation: {
    "@type": "Place",
    address: {
      "@type": "PostalAddress",
      addressCountry: "Ghana",
      addressLocality: "Kumasi",
    },
  },
};
